CREATE DATABASE BD_BEAUTY
GO
USE BD_BEAUTY
GO
CREATE TABLE ESTADO(
	UF VARCHAR(2) NOT NULL,
	NOME NVARCHAR(MAX) NOT NULL
	CONSTRAINT PK_UF PRIMARY KEY (UF)
)
GO
CREATE TABLE CIDADE(
	PK_CODIGO INT NOT NULL,
	IBGE INT NOT NULL,
	NOME NVARCHAR(MAX) NOT NULL,
	FK_UF VARCHAR(2) NOT NULL,
	CONSTRAINT PK_CODIGO_CIDADE PRIMARY KEY (PK_CODIGO),
	CONSTRAINT FK_UF FOREIGN KEY (FK_UF) REFERENCES ESTADO(UF)
)
GO
CREATE TABLE CLIENTE(
	PK_CODIGO INT NOT NULL,
	NOME NVARCHAR(MAX) NOT NULL,
	TELEFONE VARCHAR(MAX) NULL,
	CELULAR VARCHAR(MAX) NULL,
	EMAIL NVARCHAR(MAX) NULL,
	DT_NASCTO DATE NULL,
	CPF VARCHAR(11) NULL,
	RG VARCHAR(9) NULL,
	DT_CAD SMALLDATETIME NULL,
	CEP VARCHAR(9) NULL,
	ENDERECO NVARCHAR(MAX) NULL,
	NUMERO NVARCHAR(MAX) NULL,
	COMPLEMENTO NVARCHAR(MAX) NULL,
	BAIRRO NVARCHAR(MAX) NULL,
	FK_CIDADE INT NULL,
	OBS NVARCHAR(MAX) NULL,
	CONSTRAINT PK_CODIGO_CLIENTE PRIMARY KEY(PK_CODIGO)	
	--CONSTRAINT FK_CIDADE FOREIGN KEY (FK_CIDADE) REFERENCES CIDADE(PK_CODIGO)
)
GO
CREATE TABLE PROFISSIONAL(
	PK_CODIGO INT NOT NULL,
	NOME NVARCHAR(MAX) NOT NULL,
	TELEFONE VARCHAR(MAX) NULL,
	CELULAR VARCHAR(MAX) NULL,
	EMAIL NVARCHAR(MAX) NULL,
	DT_NASCTO DATE NULL,
	CPF VARCHAR(11) NULL,
	RG VARCHAR(9) NULL,
	DT_CAD SMALLDATETIME NULL,
	CEP VARCHAR(9) NULL,
	ENDERECO NVARCHAR(MAX) NULL,
	NUMERO NVARCHAR(MAX) NULL,
	COMPLEMENTO NVARCHAR(MAX) NULL,
	BAIRRO NVARCHAR(MAX) NULL,
	FK_CIDADE INT NULL,
	OBS NVARCHAR(MAX) NULL,
	CONSTRAINT PK_CODIGO_PROFISSIONAL PRIMARY KEY(PK_CODIGO)	
	--CONSTRAINT FK_CIDADE FOREIGN KEY (FK_CIDADE) REFERENCES CIDADE(PK_CODIGO)	
)
GO
CREATE TABLE TIPO_SERVICO(
	PK_CODIGO INT NOT NULL,
	DESCRICAO NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_CODIGO_TP_SERV PRIMARY KEY(PK_CODIGO)	
)
GO
CREATE TABLE SERVICO(
	PK_CODIGO INT NOT NULL,
	DESCRICAO NVARCHAR(MAX) NOT NULL,
	FK_TIPO_SERVICO INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	CUSTO DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	DESC_MAX DECIMAL(10,2) NOT NULL DEFAULT '0.00',	
	DURACAO INT NOT NULL DEFAULT '0',
	COMISSAO DECIMAL(10,2) DEFAULT '0.00',
	OBS NVARCHAR(MAX) NULL,
	CONSTRAINT PK_CODIGO_SERVICO PRIMARY KEY(PK_CODIGO),	
	CONSTRAINT FK_TIPO_SERVICO FOREIGN KEY (FK_TIPO_SERVICO) REFERENCES TIPO_SERVICO(PK_CODIGO)
)
GO
CREATE TABLE MEDIDA(
	PK_MEDIDA VARCHAR(2) NOT NULL,
	NOME NVARCHAR(MAX) NOT NULL
	CONSTRAINT PK_MEDIDA PRIMARY KEY (PK_MEDIDA)	
)
GO
CREATE TABLE TIPO_PRODUTO(
	PK_CODIGO INT NOT NULL,
	DESCRICAO NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_CODIGO_TP_PROD PRIMARY KEY(PK_CODIGO)	
)
GO
CREATE TABLE PRODUTO(
	PK_CODIGO INT NOT NULL,
	DESCRICAO NVARCHAR(MAX) NOT NULL,
	FK_TIPO_PRODUTO INT NOT NULL,
	FK_MEDIDA VARCHAR(2) NOT NULL,
	QTDE_ESTOQUE DECIMAL(10,3) NOT NULL DEFAULT '0.000',
	ESTOQUE_MINIMO INT NULL,
	VALOR DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	CUSTO DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	DESC_MAX DECIMAL(10,2) NOT NULL DEFAULT '0.00',	
	COMISSAO DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	OBS NVARCHAR(MAX) NULL,	
	CONSTRAINT PK_CODIGO_PRODUTO PRIMARY KEY(PK_CODIGO),	
	CONSTRAINT FK_TIPO_PRODUTO FOREIGN KEY (FK_TIPO_PRODUTO) REFERENCES TIPO_PRODUTO(PK_CODIGO),
	CONSTRAINT FK_MEDIDA FOREIGN KEY (FK_MEDIDA) REFERENCES MEDIDA(PK_MEDIDA)
)
GO
CREATE TABLE CAIXA(
	PK_CODIGO INT NOT NULL,
	DT_HR_ABERTURA SMALLDATETIME NOT NULL,
	DT_HR_FECHAMENTO SMALLDATETIME NOT NULL,
	VALOR_INICIAL DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	VALOR_FINAL DECIMAL(10,2) NOT NULL DEFAULT '0.00',	
	CONSTRAINT PK_CODIGO_CAIXA PRIMARY KEY(PK_CODIGO)	
)
GO
CREATE TABLE CAIXA_ENTRADA(
	PK_CODIGO INT NOT NULL,
	DESCRICAO NVARCHAR(MAX) NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	FK_CAIXA INT NOT NULL,
	CONSTRAINT PK_CODIGO_CX_ENTRADA PRIMARY KEY(PK_CODIGO),	
	CONSTRAINT FK_CAIXA FOREIGN KEY (FK_CAIXA) REFERENCES CAIXA(PK_CODIGO)
)
GO
CREATE TABLE CAIXA_SAIDA(
	PK_CODIGO INT NOT NULL,
	DESCRICAO NVARCHAR(MAX) NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	FK_CAIXA INT NOT NULL,
	CONSTRAINT PK_CODIGO_CX_SAIDA PRIMARY KEY(PK_CODIGO),	
	CONSTRAINT FK_CAIXA_2 FOREIGN KEY (FK_CAIXA) REFERENCES CAIXA(PK_CODIGO)	
)
GO
CREATE TABLE TIPO_PAGTO(
	PK_CODIGO INT NOT NULL,
	DESCRICAO NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_CODIGO_TP_PAGTO PRIMARY KEY(PK_CODIGO)	
)
GO
--TIPOS PRÉ DEFINIDOS
INSERT TIPO_PAGTO(PK_CODIGO,DESCRICAO) VALUES('1','DINHEIRO')
INSERT TIPO_PAGTO(PK_CODIGO,DESCRICAO) VALUES('2','CARTÃO')
INSERT TIPO_PAGTO(PK_CODIGO,DESCRICAO) VALUES('3','CHEQUE')
GO
CREATE TABLE FORMA_PAGTO(
	PK_CODIGO INT NOT NULL,
	DESCRICAO NVARCHAR(MAX) NOT NULL,
	FK_TIPO INT NOT NULL,
	CONSTRAINT PK_CODIGO_FORMA_PAGTO PRIMARY KEY(PK_CODIGO),
	CONSTRAINT FK_TIPO FOREIGN KEY (FK_TIPO) REFERENCES TIPO_PAGTO(PK_CODIGO)	
)
GO
CREATE TABLE COMANDA(
	PK_CODIGO INT NOT NULL,
	DATA SMALLDATETIME NOT NULL,
	FK_CLIENTE INT,
	FK_PROFISSIONAL INT,
	OBS NVARCHAR(MAX) NULL,
	CONSTRAINT PK_CODIGO_COMANDA PRIMARY KEY(PK_CODIGO),
	CONSTRAINT FK_CLIENTE FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTE(PK_CODIGO),
	CONSTRAINT FK_PROFISSIONAL FOREIGN KEY (FK_PROFISSIONAL) REFERENCES PROFISSIONAL(PK_CODIGO)
)
GO
CREATE TABLE ITEM_COMANDA(
	PK_CODIGO INT NOT NULL,
	FK_COMANDA INT NOT NULL,	
	COD_PROD_SERV INT NOT NULL,--CODIGO DO PRODUTO OU SERVIÇO
	PROD_SERV VARCHAR(1) NOT NULL,-- S(serviço) ou P(produto)
	QUANTIDADE DECIMAL(10,3) NOT NULL DEFAULT '0.000',
	VALOR DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	DESC_ITEM DECIMAL(10,2) NOT NULL DEFAULT '0.00',		
	CONSTRAINT PK_CODIGO_ITEM_COMANDA PRIMARY KEY(PK_CODIGO),
	CONSTRAINT FK_COMANDA FOREIGN KEY (FK_COMANDA) REFERENCES COMANDA(PK_CODIGO)
)
GO
CREATE TABLE PARCELA_COMANDA(
	PK_CODIGO INT NOT NULL,
	FK_COMANDA INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	FK_FORMA_PAGTO INT NOT NULL,
	QTDE_PARCELAS INT NOT NULL DEFAULT '1',
	CONSTRAINT PK_CODIGO_PARC_COMANDA PRIMARY KEY(PK_CODIGO),
	CONSTRAINT FK_COMANDA_2 FOREIGN KEY (FK_COMANDA) REFERENCES COMANDA(PK_CODIGO),
	CONSTRAINT FK_FORMA_PAGTO FOREIGN KEY(FK_FORMA_PAGTO) REFERENCES FORMA_PAGTO(PK_CODIGO)
)
GO
CREATE TABLE CRECEBER(
	PK_CODIGO INT NOT NULL,
	NOTA_FICAL INT NOT NULL UNIQUE,
	SERIE VARCHAR(2) NOT NULL,
	FK_CLIENTE INT,
	DT_EMISSAO SMALLDATETIME NOT NULL,
	DT_VENCIMENTO SMALLDATETIME NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	DT_PAGAMENTO SMALLDATETIME NOT NULL,
	CONSTRAINT PK_CODIGO_CRECEBER PRIMARY KEY(PK_CODIGO),
	CONSTRAINT FK_CLIENTE_2 FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTE(PK_CODIGO)		
)
GO
CREATE TABLE CHEQUE(
	PK_CODIGO INT NOT NULL,
	NRO INT NOT NULL UNIQUE,
	BANCO CHAR(3) NOT NULL,--CADASTRAR EM UMA TABELA
	FK_CLIENTE INT,
	DT_EMISSAO SMALLDATETIME NOT NULL,
	DT_VENCIMENTO SMALLDATETIME NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	SITUACAO BIT NOT NULL--???,
	CONSTRAINT PK_CODIGO_CHEQUE PRIMARY KEY(PK_CODIGO),
	CONSTRAINT FK_CLIENTE_3 FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTE(PK_CODIGO)
)
GO
CREATE TABLE USUARIO(
	PK_CODIGO INT NOT NULL,
	NOME NVARCHAR(MAX) NOT NULL,
	SENHA NVARCHAR(MAX) NOT NULL,
	ULTIMO_ACESSO SMALLDATETIME NOT NULL,
	CONSTRAINT PK_CODIGO_USUARIO PRIMARY KEY(PK_CODIGO)
)

INSERT USUARIO (PK_CODIGO,NOME,SENHA,ULTIMO_ACESSO) VALUES('1','ADMINISTRADOR','6z7Eal6R1yzTEZS62pXv3Js0hn1r4kYiZm75hmheTXQ=',GETDATE())